---
# handlers file for ashokc.filebeat

- name: restart filebeat
  service: name=filebeat state=restarted enabled={{ filebeat_enabled_on_boot }}

- name: reload systemd configuration
  command: systemctl daemon-reload

